#!/bin/bash
# set -E
#
#handle_error() {
#    local retval=$?
#    local line=$1
#    echo "Failed at $line: $BASH_COMMAND"
#    exit $retval
#}
#trap 'handle_error $LINENO' ERR


warn() {
    echo "$@" >&2;
}

debug() {
    if "${DEBUG}"; then
        warn "$@"
    fi
}


# defaults
DEBUG=false
scriptsDir="scripts"
cacheDir=".cache"
projectDir=$(dirname "$0")

# parse options
while getopts "ds:" opt; do
    case "${opt}" in
        d)
            DEBUG=true
            ;;
        s)
            scriptsDir="${OPTARG}"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            ;;
    esac
done

# Allow specified directories to be relative
if [[ ! $scriptsDir = /* ]]; then
    scriptsDir="$(pwd)/$scriptsDir"
fi

if [[ ! $cacheDir = /* ]]; then
    cacheDir="$(pwd)/$cacheDir"
fi

debug "scriptsDir: $scriptsDir  cacheDir $cacheDir"

# parse positional arguments after options
shift $((OPTIND-1))

# check for filename
filename="$1"
if [[ -z "${filename}" ]]; then
    warn "No filename provided";
    exit 1;
fi
extension="${filename##*.}"

if [[ ! -f "$filename" ]]; then
    warn "File $filename does not exist";
    exit 1;
fi


# Given an input path and a script, obtain the complete results - stdout, stderr, exit code -
# as if we ran that script and validation on exactly that input. This may be obtained
# from cache. The cache is keyed by the hashed content of the input file and script file.
#
# So, for the script && validation:
#   Echoes the path to a file caching the stdout;
#   Echoes the stderr to stderr.
#   Returns the exit code of the script && validation.
getCachedValidatedResultPath() {
    debug "";
    debug "========";

    local contentPath script
    script="$1"
    contentPath="$2"

    warn "running script $script on $contentPath"
    cachedStdoutPath=$("${projectDir}/cache.sh" "${script}" "${contentPath}")
    exitCode=$?

    warn "success was $exitCode"
    
    # we're back to running the validator every time...
    if [[ -n "$validator" ]]; then
        warn "running validator"
        warn "  -> ${validator} "
        warn "  on ${cachedStdoutPath}"
        if [[ ! -f "${cachedStdoutPath}" ]]; then
            warn "cached stdout path ${cachedStdoutPath} does not exist"
            exit 1
        fi
        if [[ ! -x "${validator}" ]]; then
            warn "validator ${validator} is not executable"
            exit 1
        fi
        "${validator}" < "${cachedStdoutPath}" 1>&2
        exitCode=$?
    fi
    return $exitCode
}

# Get the validator for this extension, if there is one
validatorsDir="$scriptsDir/validators"
if [[ -d "$validatorsDir" ]]; then
    validatorPath="${validatorsDir}/${extension}"
    if [[ -f "$validatorPath" && -x "$validatorPath" ]]; then
        validator="$validatorPath"
    fi
fi

# Build the array of scripts
scripts=();
if [[ -n "${extension}" ]]; then
    if [[ -d "${scriptsDir}/${extension}" ]]; then        
        # The first "script" is a no-op, cat, because we need to validate the file as is.
        scripts=('/bin/cat');
        while IFS=  read -r -d $'\0' script; do
            scripts+=("${script}")
        done < <(find "${scriptsDir}/${extension}" -type f -perm -u=x -prune -print0 | sort -z)
    fi
fi

# Sometimes a script very late in the chain will need to know the original path - for instance, something 
# that builds navigation, involving files in the same directory. We pass this in an environment variable.
PERMAWEB_SOURCE_PATH=$(realpath -s "${filename}");
export PERMAWEB_SOURCE_PATH;

# Iterate through the array of scripts for this content. If a script fails, discard its results. 
# Eventually we will have a path to a file that represents only the successful transformations of the original file.
contentPath=${filename};
for script in "${scripts[@]}"; do
    debug "Current input path is ${contentPath}";

    newContentPath=$(getCachedValidatedResultPath "${script}" "${contentPath}");
    returnCode=$?
    debug "return code from result is ${returnCode}";
    if [[ $returnCode -ne 0 ]]; then
        debug "Script ${script} failed; skipping";
        continue;
    fi

    debug "new input path is ${newContentPath}";
    contentPath="${newContentPath}";
done

# Print the successful results of the transformations
debug "final content path is ${contentPath}"
cat "$contentPath";