#!/usr/bin/env node

const fs = require('fs');
const { JSDOM: jsdom } = require("jsdom");

const footerString = `<footer>
<p>Generated by <a href="https://github.com/neilk/permaweb">permaweb</a>.
Copyright ${(new Date()).getFullYear()} Neil Kandalgaonkar.</p>
</footer>`;

let footer = jsdom.fragment(footerString);


async function main() {
    let dom = new jsdom(fs.readFileSync('/dev/stdin').toString());
    const { document } = dom.window;

    let body = document.querySelectorAll('body')[0];
    body.append(footer);

    process.stdout.write(dom.serialize().trim());
}

main().catch(console.error);


