#!/usr/bin/env bash

# TODO why does this try to make a network connection? On a plane, with busted wifi,
# this blocked. But if wifi was turned off it succeeded

# Unclear why we need to explicitly specify the config file .htmlvalidate.json; it's
# supposed to search upwards in directories for that file?  

set -e 
cd "$(dirname "$0")" || exit 1
npx html-validate -c .htmlvalidate.json --stdin 1>&2 